//
// Created by Zhou on 11/07/2023.
//

#ifndef PROJECT_COMPOSEDCALCULATOR_MAIN_H
#define PROJECT_COMPOSEDCALCULATOR_MAIN_H

int ComposedCalculator_main();

#endif //PROJECT_COMPOSEDCALCULATOR_MAIN_H
